# Generated by Django 5.2.7 on 2025-10-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultations",
            "0081_rename_parent_selectedtheme_crosscuttingtheme_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="code",
            field=models.SlugField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="slug",
            field=models.SlugField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
